#ifndef DOWNSTAIRMAN_BASIC_H
#define DOWNSTAIRMAN_BASIC_H

#include "allegro5\allegro.h"

extern ALLEGRO_COLOR WHITE;
extern ALLEGRO_COLOR BLACK;
extern ALLEGRO_COLOR BLUE;
extern ALLEGRO_COLOR GREEN;
extern ALLEGRO_COLOR RED;
extern ALLEGRO_COLOR YELLOW;

#endif